version: "3"
services:
    app:
        container_name: MangList
        ports:
            - "80:80"
        build: .
        restart: unless-stopped
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
